### ISSUE TITLE
'cifar-10c': Could not find 'user/username', cfg.user.ckpt_dir 

### ISSUE THREAD

**Issue by vijay7anand** [anniesch/surgical-finetuning#1]
Hello,

While trying to run the following command:
python3 main.py --config-name='cifar-10c' args.train_n=1000 args.seed=0 data.corruption_types=['defocus_blur'] wandb.use=True

I am getting the following error: 
cfg.user.ckpt_dir also not found
In 'cifar-10c': Could not find 'user/username

Could you please help me resolve this issue, or let me know what to add for path of checkpoint directory and username.

**Comment by vijay7anand** [comment]
Solved!!!

**Comment by min-seon-kim** [comment]
@vijay7anand How did you resolve this issue?
